# Generated by Django 5.2.15 on 2026-09-07 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0005_company_ai_parsing_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_key', models.CharField(db_index=True, max_length=150)),
                ('handler_version', models.PositiveIntegerField(default=1)),
                ('queue_name', models.CharField(db_index=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('claimed', 'Claimed'), ('running', 'Running'), ('retrying', 'Retrying'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('priority', models.IntegerField(db_index=True, default=100)),
                ('payload', models.JSONField(default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=255)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('available_at', models.DateTimeField(db_index=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('locked_by', models.CharField(blank=True, db_index=True, max_length=255)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('last_traceback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='background_tasks', to='tenancy.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='background_tasks_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'task_management_background_task',
                'ordering': ['priority', 'available_at', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackgroundTaskEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('enqueued', 'Enqueued'), ('claimed', 'Claimed'), ('started', 'Started'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('retry_scheduled', 'Retry Scheduled'), ('lock_released', 'Lock Released'), ('cancelled', 'Cancelled'), ('manually_retried', 'Manually Retried')], max_length=50)),
                ('worker_id', models.CharField(blank=True, max_length=255)),
                ('attempt_number', models.PositiveIntegerField(default=0)),
                ('message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('traceback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='task_management.backgroundtask')),
            ],
            options={
                'db_table': 'task_management_background_task_event',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BackgroundTaskSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('task_key', models.CharField(max_length=150)),
                ('handler_version', models.PositiveIntegerField(default=1)),
                ('queue_name', models.CharField(max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('schedule_type', models.CharField(choices=[('interval', 'Interval'), ('one_off', 'One Off')], max_length=20)),
                ('interval_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('run_at', models.DateTimeField(blank=True, null=True)),
                ('cron_expression', models.CharField(blank=True, max_length=100)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_enqueued_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('max_concurrent_enqueues', models.PositiveIntegerField(default=1)),
                ('dedupe_window_seconds', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='background_task_schedules', to='tenancy.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='background_task_schedules_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'task_management_background_task_schedule',
                'ordering': ['next_run_at', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='backgroundtask',
            index=models.Index(fields=['queue_name', 'status', 'available_at'], name='task_manage_queue_n_ff81f2_idx'),
        ),
        migrations.AddIndex(
            model_name='backgroundtask',
            index=models.Index(fields=['status', 'heartbeat_at'], name='task_manage_status_4e7ff6_idx'),
        ),
        migrations.AddIndex(
            model_name='backgroundtask',
            index=models.Index(fields=['company', 'created_at'], name='task_manage_company_cd4b2d_idx'),
        ),
        migrations.AddConstraint(
            model_name='backgroundtask',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('pending', 'claimed', 'running', 'retrying')), models.Q(('idempotency_key', ''), _negated=True)), fields=('task_key', 'idempotency_key'), name='task_active_idempotency_unique'),
        ),
        migrations.AddIndex(
            model_name='backgroundtaskschedule',
            index=models.Index(fields=['is_active', 'next_run_at'], name='task_manage_is_acti_08b73c_idx'),
        ),
    ]
