# Generated by Django 5.2.15 on 2026-06-23 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=50)),
                ('session_status', models.CharField(choices=[('pending_qr', 'Pending QR'), ('qr_generated', 'QR Generated'), ('connected', 'Connected'), ('disconnected', 'Disconnected'), ('logged_out', 'Logged Out'), ('error', 'Error')], default='pending_qr', max_length=50)),
                ('worker_session_id', models.CharField(blank=True, max_length=255)),
                ('last_connected_at', models.DateTimeField(blank=True, null=True)),
                ('last_disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'whatsapp_account',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='whatsapp_bridge.whatsappaccount')),
            ],
            options={
                'db_table': 'whatsapp_sync_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wa_contact_id', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=50)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('push_name', models.CharField(blank=True, max_length=255)),
                ('is_business', models.BooleanField(default=False)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='whatsapp_bridge.whatsappaccount')),
            ],
            options={
                'db_table': 'whatsapp_contact',
                'ordering': ['display_name'],
                'unique_together': {('account', 'wa_contact_id')},
            },
        ),
        migrations.CreateModel(
            name='WhatsAppChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wa_chat_id', models.CharField(max_length=255)),
                ('chat_type', models.CharField(choices=[('individual', 'Individual'), ('group', 'Group')], max_length=50)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('unread_count', models.IntegerField(default=0)),
                ('is_archived', models.BooleanField(default=False)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='whatsapp_bridge.whatsappaccount')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chats', to='whatsapp_bridge.whatsappcontact')),
            ],
            options={
                'db_table': 'whatsapp_chat',
                'ordering': ['-last_message_at'],
                'unique_together': {('account', 'wa_chat_id')},
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_message_id', models.CharField(max_length=255)),
                ('sender_number', models.CharField(blank=True, max_length=50)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=20)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('document', 'Document'), ('sticker', 'Sticker'), ('location', 'Location'), ('contact', 'Contact'), ('unknown', 'Unknown')], max_length=50)),
                ('message_text', models.TextField(blank=True)),
                ('message_time', models.DateTimeField()),
                ('has_media', models.BooleanField(default=False)),
                ('media_mime_type', models.CharField(blank=True, max_length=255)),
                ('media_file_name', models.CharField(blank=True, max_length=255)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='whatsapp_bridge.whatsappaccount')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='whatsapp_bridge.whatsappchat')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='whatsapp_bridge.whatsappcontact')),
            ],
            options={
                'db_table': 'whatsapp_message',
                'ordering': ['-message_time'],
                'indexes': [models.Index(fields=['account', 'message_time'], name='whatsapp_me_account_5539e5_idx'), models.Index(fields=['chat', 'message_time'], name='whatsapp_me_chat_id_489073_idx'), models.Index(fields=['direction'], name='whatsapp_me_directi_426062_idx'), models.Index(fields=['message_type'], name='whatsapp_me_message_b7c7f1_idx')],
                'unique_together': {('account', 'provider_message_id')},
            },
        ),
    ]
