# Generated by Django 5.2.15 on 2026-06-26 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bridge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='media_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
