# Generated by Django 5.2.15 on 2026-06-26 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bridge', '0003_account_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappmessage',
            name='media_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
