# Generated by Django 5.2.15 on 2026-06-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bridge', '0005_fix_lid_phone_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappaccount',
            name='auto_download_media',
            field=models.BooleanField(default=True),
        ),
    ]
