# Generated by Django 5.2.15 on 2026-06-30 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bridge', '0011_backfill_groups_from_chats'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='droppedmessage',
            new_name='whatsapp_dr_account_fadf6b_idx',
            old_name='whatsapp_dr_account_idx',
        ),
    ]
