# Generated by Django 5.2.15 on 2026-07-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bridge', '0014_ai_parsing_default_off'),
    ]

    operations = [
        migrations.AddField(
            model_name='droppedmessage',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='droppedmessage',
            index=models.Index(fields=['account', 'msg_id'], name='whatsapp_dr_account_2185a1_idx'),
        ),
    ]
