# Generated by Django 5.2.15 on 2026-07-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bridge', '0015_droppedmessage_resolved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappcontact',
            name='category',
            field=models.CharField(blank=True, choices=[('supplier', 'Supplier'), ('customer', 'Customer')], max_length=20),
        ),
    ]
