# Generated by Django 5.2.15 on 2026-07-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bridge', '0016_whatsappcontact_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappcontact',
            name='category',
            field=models.CharField(blank=True, choices=[('supplier', 'Supplier'), ('customer', 'Customer'), ('both', 'Both (Supplier & Customer)')], max_length=20),
        ),
    ]
