# Generated by Django 5.2.15 on 2026-07-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bridge', '0017_alter_whatsappcontact_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappaccount',
            name='connection_unhealthy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whatsappaccount',
            name='connection_unhealthy_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='whatsappaccount',
            name='connection_unhealthy_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
