# Generated by Django 5.2.15 on 2026-07-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bridge', '0018_whatsappaccount_connection_unhealthy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappaccount',
            name='connection_unhealthy_reason',
            field=models.TextField(blank=True),
        ),
    ]
