# Generated by Django 5.2.15 on 2026-07-11 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bridge', '0019_alter_whatsappaccount_connection_unhealthy_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('decrypt_failure', 'Message decrypt failure'), ('handshake_timeout', 'Connection handshake timeout'), ('history_build_failed', 'History message dropped while building payload'), ('batch_persist_failed', 'Message lost persisting a history/live batch'), ('batch_partial_failure', 'Batch ingest reported partial errors'), ('drop_report_failed', 'Worker could not report a dropped message to Django'), ('uncaught_exception', 'Uncaught exception in a worker event handler'), ('other', 'Other')], max_length=30)),
                ('severity', models.CharField(choices=[('warning', 'Warning'), ('error', 'Error')], default='warning', max_length=10)),
                ('message', models.TextField()),
                ('context', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worker_alerts', to='whatsapp_bridge.whatsappaccount')),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'whatsapp_worker_alert',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['account', 'created_at'], name='whatsapp_wo_account_d28ac7_idx'), models.Index(fields=['alert_type', 'created_at'], name='whatsapp_wo_alert_t_7ab938_idx'), models.Index(fields=['acknowledged_at'], name='whatsapp_wo_acknowl_340171_idx')],
            },
        ),
    ]
