# Generated by Django 5.2.15 on 2026-07-13 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bridge', '0020_workeralert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StuckReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_jid', models.CharField(max_length=255)),
                ('participant', models.CharField(blank=True, max_length=255)),
                ('message_id', models.CharField(max_length=255)),
                ('from_me', models.BooleanField(default=True)),
                ('context', models.JSONField(blank=True, null=True)),
                ('occurrence_count', models.PositiveIntegerField(default=1)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stuck_receipts', to='whatsapp_bridge.whatsappaccount')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'whatsapp_stuck_receipt',
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['account', 'resolved_at'], name='whatsapp_st_account_559791_idx')],
                'constraints': [models.UniqueConstraint(fields=('account', 'remote_jid', 'message_id'), name='unique_stuck_receipt_per_message')],
            },
        ),
    ]
