# Generated by Django 5.2.15 on 2026-07-21 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bridge', '0021_stuckreceipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workeralert',
            name='alert_type',
            field=models.CharField(choices=[('decrypt_failure', 'Message decrypt failure'), ('handshake_timeout', 'Connection handshake timeout'), ('history_build_failed', 'History message dropped while building payload'), ('batch_persist_failed', 'Message lost persisting a history/live batch'), ('batch_partial_failure', 'Batch ingest reported partial errors'), ('drop_report_failed', 'Worker could not report a dropped message to Django'), ('unresolved_message_failed', 'Worker could not preserve an unresolved (LID-blocked) message'), ('uncaught_exception', 'Uncaught exception in a worker event handler'), ('other', 'Other')], max_length=30),
        ),
        migrations.CreateModel(
            name='WhatsAppUnresolvedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_jid', models.CharField(max_length=255)),
                ('participant_jid', models.CharField(blank=True, max_length=255)),
                ('lid_jid', models.CharField(blank=True, db_index=True, max_length=255)),
                ('from_me', models.BooleanField(default=False)),
                ('direction', models.CharField(blank=True, max_length=10)),
                ('message_type', models.CharField(default='unknown', max_length=20)),
                ('message_text', models.TextField(blank=True)),
                ('has_media', models.BooleanField(default=False)),
                ('message_time', models.DateTimeField(blank=True, null=True)),
                ('push_name', models.CharField(blank=True, max_length=255)),
                ('is_history', models.BooleanField(default=False)),
                ('reason', models.CharField(default='unresolvable_lid', max_length=50)),
                ('raw_key', models.JSONField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('resolution_status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('failed', 'Failed')], db_index=True, default='pending', max_length=10)),
                ('resolution_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unresolved_messages', to='whatsapp_bridge.whatsappaccount')),
                ('resolved_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='whatsapp_bridge.whatsappcontact')),
                ('resolved_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='whatsapp_bridge.whatsappmessage')),
            ],
            options={
                'db_table': 'whatsapp_unresolved_message',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['account', 'resolution_status'], name='whatsapp_un_account_af9726_idx'), models.Index(fields=['account', 'lid_jid', 'resolution_status'], name='whatsapp_un_account_4cc7c9_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('provider_message_id__isnull', False)), fields=('account', 'provider_message_id'), name='unique_unresolved_message_per_account_provider_id')],
            },
        ),
    ]
