# Generated by Django 5.2.15 on 2026-07-22 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0002_seed_initial_tenancy_data'),
        ('whatsapp_bridge', '0022_unresolved_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappaccount',
            name='communication_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_account', to='tenancy.communicationaccount'),
        ),
        migrations.AddField(
            model_name='whatsappaccount',
            name='primary_endpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenancy.accountendpoint'),
        ),
        migrations.AddField(
            model_name='whatsappcontact',
            name='company_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_contacts', to='tenancy.companycontact'),
        ),
    ]
