# Generated by Django 5.2.15 on 2026-07-29 16:03

import django.db.models.deletion
from django.db import migrations, models


def backfill_contact_role_tags(apps, schema_editor):
    WhatsAppContact = apps.get_model('whatsapp_bridge', 'WhatsAppContact')
    ContactRoleTag = apps.get_model('whatsapp_bridge', 'ContactRoleTag')

    contacts = (
        WhatsAppContact.objects
        .select_related('account__communication_account')
        .exclude(category='')
    )
    rows = []
    for contact in contacts.iterator():
        roles = []
        if contact.category == 'supplier':
            roles = ['supplier']
        elif contact.category == 'customer':
            roles = ['customer']
        elif contact.category == 'both':
            roles = ['supplier', 'customer']
        if not roles:
            continue

        communication_account = getattr(contact.account, 'communication_account', None)
        company_id = communication_account.company_id if communication_account else None
        for role in roles:
            rows.append(ContactRoleTag(
                company_id=company_id,
                contact_id=contact.pk,
                role=role,
                source='migration',
            ))

    ContactRoleTag.objects.bulk_create(rows, ignore_conflicts=True, batch_size=1000)


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0003_backfill_existing_tenant_links'),
        ('whatsapp_bridge', '0023_whatsappaccount_communication_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRoleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('supplier', 'Supplier'), ('customer', 'Customer')], max_length=20)),
                ('source', models.CharField(choices=[('migration', 'Migration'), ('manual', 'Manual'), ('ai_suggestion', 'AI Suggestion')], default='manual', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_role_tags', to='tenancy.company')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_tags', to='whatsapp_bridge.whatsappcontact')),
            ],
            options={
                'db_table': 'whatsapp_contact_role_tag',
                'indexes': [models.Index(fields=['company', 'role'], name='wa_role_company_role_idx')],
                'constraints': [models.UniqueConstraint(fields=('contact', 'role'), name='whatsapp_contact_role_tag_contact_role_uniq')],
            },
        ),
        migrations.RunPython(backfill_contact_role_tags, migrations.RunPython.noop),
    ]
