# Generated by Django 5.2.15 on 2026-08-02 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bridge', '0025_baileys_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappaccount',
            name='classification_version_override',
            field=models.CharField(choices=[('inherit', 'Inherit company default'), ('v1', 'Classification V1'), ('v2', 'Classification V2')], default='inherit', max_length=10),
        ),
    ]
