# Generated by Django 5.2.15 on 2026-08-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bridge', '0026_whatsappaccount_classification_version_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappaccount',
            name='last_worker_heartbeat_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
