# Generated by Django 5.2.15 on 2026-09-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bridge', '0027_whatsappaccount_last_worker_heartbeat_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappaccount',
            name='account_interval_ms',
            field=models.PositiveIntegerField(default=5000),
        ),
        migrations.AddField(
            model_name='whatsappaccount',
            name='allow_concurrent_sends',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whatsappaccount',
            name='direct_sending_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whatsappaccount',
            name='group_sending_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whatsappaccount',
            name='max_concurrent_sends',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='whatsappaccount',
            name='outbound_sending_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whatsappaccount',
            name='recipient_interval_ms',
            field=models.PositiveIntegerField(default=5000),
        ),
        migrations.AddField(
            model_name='whatsappaccount',
            name='unknown_new_chat_policy',
            field=models.CharField(choices=[('block', 'Block sending'), ('allow', 'Allow after confirmation')], default='block', max_length=10),
        ),
    ]
