# Generated by Django 5.2.15 on 2026-09-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bridge', '0028_whatsappaccount_account_interval_ms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappgroup',
            name='account_is_participant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whatsappgroup',
            name='account_participant_role',
            field=models.CharField(blank=True, choices=[('member', 'Member'), ('admin', 'Admin'), ('superadmin', 'Superadmin')], max_length=20),
        ),
        migrations.AddField(
            model_name='whatsappgroup',
            name='announce',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whatsappgroup',
            name='can_send',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whatsappgroup',
            name='is_community_announcement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whatsappgroup',
            name='metadata_refreshed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whatsappgroup',
            name='restrict',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whatsappgroup',
            name='send_block_reason',
            field=models.CharField(default='group_metadata_unavailable', max_length=100),
        ),
    ]
