# Generated by Django 5.2.15 on 2026-09-16 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bridge', '0029_whatsappgroup_account_is_participant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppAccountCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='baileys_v7', max_length=50)),
                ('total_quota', models.PositiveIntegerField(blank=True, null=True)),
                ('used_quota', models.PositiveIntegerField(blank=True, null=True)),
                ('cycle_started_at', models.DateTimeField(blank=True, null=True)),
                ('cycle_ends_at', models.DateTimeField(blank=True, null=True)),
                ('server_sent_at', models.DateTimeField(blank=True, null=True)),
                ('capping_status', models.CharField(blank=True, max_length=40)),
                ('ote_status', models.CharField(blank=True, max_length=50)),
                ('mv_status', models.CharField(blank=True, max_length=50)),
                ('cap_fetch_status', models.CharField(choices=[('unknown', 'Unknown'), ('available', 'Available'), ('unavailable', 'Unavailable'), ('unsupported', 'Unsupported')], default='unknown', max_length=20)),
                ('cap_checked_at', models.DateTimeField(blank=True, null=True)),
                ('cap_updated_at', models.DateTimeField(blank=True, null=True)),
                ('cap_error', models.TextField(blank=True)),
                ('reachout_lock_active', models.BooleanField(default=False)),
                ('reachout_lock_ends_at', models.DateTimeField(blank=True, null=True)),
                ('reachout_enforcement_type', models.CharField(blank=True, max_length=100)),
                ('reachout_fetch_status', models.CharField(choices=[('unknown', 'Unknown'), ('available', 'Available'), ('unavailable', 'Unavailable'), ('unsupported', 'Unsupported')], default='unknown', max_length=20)),
                ('reachout_checked_at', models.DateTimeField(blank=True, null=True)),
                ('reachout_updated_at', models.DateTimeField(blank=True, null=True)),
                ('reachout_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='message_capacity', to='whatsapp_bridge.whatsappaccount')),
            ],
            options={
                'db_table': 'whatsapp_account_capacity',
            },
        ),
    ]
