# Generated by Django 5.2.15 on 2026-06-30 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('whatsapp_bridge', '0012_rename_whatsapp_dr_account_idx_whatsapp_dr_account_fadf6b_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('aliases', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'trading_product',
                'ordering': ['brand', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquiry_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], db_index=True, max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('deal_done', 'Deal Done')], db_index=True, default='open', max_length=20)),
                ('products', models.JSONField(default=list)),
                ('summary', models.TextField()),
                ('remarks', models.TextField(blank=True)),
                ('dedup_key', models.CharField(db_index=True, max_length=512)),
                ('source_type', models.CharField(choices=[('direct', 'Direct'), ('group', 'Group'), ('community', 'Community')], max_length=20)),
                ('first_seen_at', models.DateTimeField(db_index=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='whatsapp_bridge.whatsappaccount')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='whatsapp_bridge.whatsappcontact')),
            ],
            options={
                'db_table': 'trading_inquiry',
                'ordering': ['-first_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.JSONField(default=list)),
                ('products', models.JSONField(default=list)),
                ('is_inquiry', models.BooleanField(default=False)),
                ('inquiry_type', models.CharField(blank=True, choices=[('buy', 'Buy'), ('sell', 'Sell'), ('both', 'Both')], max_length=10)),
                ('ai_summary', models.TextField(blank=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('classified_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classification', to='whatsapp_bridge.whatsappmessage')),
            ],
            options={
                'db_table': 'trading_message_classification',
            },
        ),
        migrations.CreateModel(
            name='InquiryMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiry_messages', to='trading.inquiry')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiry_links', to='whatsapp_bridge.whatsappmessage')),
            ],
            options={
                'db_table': 'trading_inquiry_message',
                'unique_together': {('inquiry', 'message')},
            },
        ),
    ]
