# Generated by Django 5.2.15 on 2026-07-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_prompt_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('classification', 'Inquiry Classification'), ('product_extraction', 'Product Extraction')], db_index=True, max_length=50)),
                ('provider', models.CharField(blank=True, max_length=50)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('messages', models.JSONField()),
                ('response', models.TextField(blank=True)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('duration_ms', models.IntegerField(default=0)),
                ('success', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True)),
                ('wa_message_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'trading_agent_call_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
