# Generated by Django 5.2.15 on 2026-07-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_agent_call_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageclassification',
            name='dedup_key',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
