# Generated by Django 5.2.15 on 2026-07-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_add_inventory_fields_to_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('quoted_waiting', 'Quoted - Waiting'), ('price_high', 'Price High'), ('no_stock', 'No Stock'), ('not_dealing', 'Product Not Dealing with ATM'), ('irrelevant', 'Irrelevant'), ('closed', 'Closed'), ('deal_done', 'Deal Done')], db_index=True, default='open', max_length=20),
        ),
    ]
