# Generated by Django 5.2.15 on 2026-07-06 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0007_alter_inquiry_status'),
        ('whatsapp_bridge', '0015_droppedmessage_resolved_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiParsingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('sent', 'Sent for AI Parsing'), ('skipped', 'Skipped')], max_length=10)),
                ('skip_reason', models.CharField(blank=True, choices=[('no_text', 'No text content'), ('outbound', 'Outbound message'), ('too_old', 'Older than 24h (history sync)'), ('chat_disabled', 'AI parsing off for this chat'), ('account_disabled', 'AI parsing off for this account')], max_length=30)),
                ('message_preview', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_parsing_logs', to='whatsapp_bridge.whatsappaccount')),
                ('chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_parsing_logs', to='whatsapp_bridge.whatsappchat')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_parsing_log', to='whatsapp_bridge.whatsappmessage')),
            ],
            options={
                'db_table': 'trading_ai_parsing_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['account', 'created_at'], name='trading_ai__account_3238b3_idx'), models.Index(fields=['status', 'created_at'], name='trading_ai__status_6b9d34_idx')],
            },
        ),
    ]
