# Generated by Django 5.2.15 on 2026-07-07 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0008_aiparsinglog'),
        ('whatsapp_bridge', '0016_whatsappcontact_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyingInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('quantity', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buying_inquiries', to='whatsapp_bridge.whatsappaccount')),
            ],
            options={
                'verbose_name_plural': 'buying inquiries',
                'db_table': 'trading_buying_inquiry',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_asked', 'Not Asked'), ('asked', 'Asked - Waiting'), ('quoted', 'Quoted'), ('declined', 'Declined / No Stock')], default='not_asked', max_length=10)),
                ('asked_at', models.DateTimeField(blank=True, null=True)),
                ('quoted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('quoted_currency', models.CharField(blank=True, default='USD', max_length=10)),
                ('quote_note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buying_inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_quotes', to='trading.buyinginquiry')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_requests', to='whatsapp_bridge.whatsappcontact')),
            ],
            options={
                'db_table': 'trading_supplier_quote',
                'ordering': ['id'],
                'unique_together': {('buying_inquiry', 'supplier')},
            },
        ),
    ]
