# Generated by Django 5.2.15 on 2026-07-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0010_alter_inquiry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='suggested_contact_category',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='messageclassification',
            name='suggested_contact_category',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
