# Generated by Django 5.2.15 on 2026-07-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0011_inquiry_suggested_contact_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormattedPriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'trading_formatted_price_list',
            },
        ),
    ]
