# Generated by Django 5.2.15 on 2026-07-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0012_formattedpricelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiparsinglog',
            name='skip_reason',
            field=models.CharField(blank=True, choices=[('no_text', 'No text content'), ('outbound', 'Outbound message'), ('too_old', 'Older than 24h (history sync)'), ('chat_disabled', 'AI parsing off for this chat'), ('account_disabled', 'AI parsing off for this account'), ('duplicate_broadcast', 'Duplicate of a recent group broadcast')], max_length=30),
        ),
    ]
