# Generated by Django 5.2.15 on 2026-07-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0013_alter_aiparsinglog_skip_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='classification_rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5),
        ),
    ]
