# Generated by Django 5.2.15 on 2026-07-13 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0014_inquiry_classification_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alias_set', to='trading.product')),
            ],
            options={
                'db_table': 'trading_product_alias',
                'ordering': ['alias'],
                'constraints': [models.UniqueConstraint(fields=('product', 'alias'), name='unique_product_alias')],
            },
        ),
    ]
