# Generated by Django 5.2.15 on 2026-07-13 22:21

from django.db import migrations


def copy_aliases_forward(apps, schema_editor):
    Product = apps.get_model('trading', 'Product')
    ProductAlias = apps.get_model('trading', 'ProductAlias')

    rows = []
    for product in Product.objects.exclude(aliases=[]).iterator():
        seen = set()
        for raw in (product.aliases or []):
            if not isinstance(raw, str):
                continue
            alias = raw.strip()
            key = alias.lower()
            if not alias or key in seen:
                continue
            seen.add(key)
            rows.append(ProductAlias(product=product, alias=alias))

    if rows:
        ProductAlias.objects.bulk_create(rows, ignore_conflicts=True)


def copy_aliases_backward(apps, schema_editor):
    Product = apps.get_model('trading', 'Product')
    ProductAlias = apps.get_model('trading', 'ProductAlias')

    for product in Product.objects.prefetch_related('alias_set').iterator():
        aliases = list(product.alias_set.values_list('alias', flat=True))
        if aliases:
            product.aliases = aliases
            product.save(update_fields=['aliases'])


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0015_productalias'),
    ]

    operations = [
        migrations.RunPython(copy_aliases_forward, copy_aliases_backward),
    ]
