# Generated by Django 5.2.15 on 2026-07-13 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0016_migrate_aliases_json_to_rows'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='aliases',
        ),
    ]
