# Generated by Django 5.2.15 on 2026-07-15 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0017_remove_product_aliases'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_set', to='trading.product')),
            ],
            options={
                'db_table': 'trading_product_attribute',
                'ordering': ['key'],
                'constraints': [models.UniqueConstraint(fields=('product', 'key'), name='unique_product_attribute_key')],
            },
        ),
    ]
