# Generated by Django 5.2.15 on 2026-07-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0020_alter_inquiry_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('requested_price', 'Requested Price'), ('quoted_waiting', 'Quoted - Waiting'), ('no_response', 'No Response'), ('price_high', 'Price High'), ('no_stock', 'No Stock'), ('currently_in_stock', 'Currently In Stock'), ('not_dealing', 'Product Not Dealing with ATM'), ('irrelevant', 'Irrelevant'), ('closed', 'Closed'), ('deal_done', 'Deal Done'), ('tracking', 'Tracking'), ('incorrect_match', 'Incorrect Match')], db_index=True, default='open', max_length=20),
        ),
    ]
