# Generated by Django 5.2.15 on 2026-07-16 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0021_alter_inquiry_status'),
        ('whatsapp_bridge', '0021_stuckreceipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('trigger_heading', models.CharField(blank=True, max_length=200)),
                ('trigger_ai_detect', models.BooleanField(default=False)),
                ('action_mode', models.CharField(choices=[('review', 'Send for review'), ('auto', 'Auto-apply')], default='review', max_length=10)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('trigger_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'trading_automation_rule',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomatedPriceCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('applied', 'Applied'), ('ignored', 'Ignored')], default='queued', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price_capture', to='whatsapp_bridge.whatsappmessage')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captures', to='trading.automationrule')),
            ],
            options={
                'db_table': 'trading_automated_price_capture',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomationRuleSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('contact', 'Contact (direct messages)'), ('group', 'Group (any member)'), ('contact_in_group', 'Specific contact within a group')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='whatsapp_bridge.whatsappcontact')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='whatsapp_bridge.whatsappgroup')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='trading.automationrule')),
            ],
            options={
                'db_table': 'trading_automation_rule_source',
            },
        ),
    ]
