# Generated by Django 5.2.15 on 2026-07-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0022_automationrule_automatedpricecapture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automatedpricecapture',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('applied', 'Applied'), ('ignored', 'Ignored'), ('test', 'Test match')], default='queued', max_length=10),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='action_mode',
            field=models.CharField(choices=[('review', 'Send for review'), ('auto', 'Auto-apply'), ('test', 'Test rule')], default='review', max_length=10),
        ),
    ]
