# Generated by Django 5.2.15 on 2026-07-22 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0002_seed_initial_tenancy_data'),
        ('trading', '0023_alter_automatedpricecapture_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='tenancy.company'),
        ),
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='tenancy.company'),
        ),
    ]
