# Generated by Django 5.2.15 on 2026-07-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0026_backfill_inquiry_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentcalllog',
            name='purpose',
            field=models.CharField(choices=[('classification', 'Inquiry Classification'), ('product_extraction', 'Product Extraction'), ('match_verification', 'Inquiry Match Verification')], db_index=True, max_length=50),
        ),
    ]
