# Generated by Django 5.2.15 on 2026-07-30 14:55

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0003_backfill_existing_tenant_links'),
        ('trading', '0027_alter_agentcalllog_purpose'),
        ('whatsapp_bridge', '0024_contactroletag'),
    ]

    operations = [
        migrations.CreateModel(
            name='InquiryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquiry_type', models.CharField(db_index=True, max_length=10)),
                ('source_product_index', models.PositiveIntegerField(blank=True, null=True)),
                ('canonical_name', models.CharField(max_length=500)),
                ('normalized_name', models.CharField(blank=True, db_index=True, max_length=500)),
                ('original_text', models.TextField(blank=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('decision_status', models.CharField(choices=[('pending', 'Pending'), ('mapped', 'Mapped'), ('created', 'Created'), ('dismissed', 'Dismissed')], db_index=True, default='pending', max_length=20)),
                ('match_status', models.CharField(choices=[('exact', 'Exact'), ('near', 'Near'), ('unmatched', 'Unmatched'), ('manual_confirmed', 'Manual Confirmed'), ('rejected', 'Rejected')], db_index=True, default='unmatched', max_length=30)),
                ('match_type', models.CharField(blank=True, max_length=20)),
                ('match_source', models.CharField(blank=True, choices=[('ai', 'AI'), ('alias', 'Alias'), ('deterministic', 'Deterministic'), ('embedding', 'Embedding'), ('manual', 'Manual'), ('backfill', 'Backfill')], db_index=True, max_length=30)),
                ('match_reason', models.TextField(blank=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=512, null=True)),
                ('embedding_model', models.CharField(blank=True, max_length=255)),
                ('embedding_metadata', models.JSONField(blank=True, null=True)),
                ('embedding_status', models.CharField(choices=[('pending', 'Pending'), ('embedded', 'Embedded'), ('error', 'Error'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=20)),
                ('embedding_error', models.TextField(blank=True)),
                ('first_seen_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiry_products', to='whatsapp_bridge.whatsappaccount')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiry_products', to='tenancy.company')),
                ('company_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiry_products', to='tenancy.companycontact')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiry_products', to='whatsapp_bridge.whatsappcontact')),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_products', to='trading.inquiry')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiry_mentions', to='trading.product')),
                ('source_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiry_products', to='whatsapp_bridge.whatsappmessage')),
            ],
            options={
                'db_table': 'trading_inquiry_product',
                'ordering': ['-first_seen_at', '-id'],
                'indexes': [models.Index(fields=['company', 'inquiry_type', 'first_seen_at'], name='inqprod_company_type_seen_idx'), models.Index(fields=['company', 'decision_status'], name='inqprod_company_decision_idx'), models.Index(fields=['company', 'match_status'], name='inqprod_company_match_idx'), models.Index(fields=['product', 'inquiry_type', 'first_seen_at'], name='inqprod_product_type_seen_idx')],
            },
        ),
    ]
