# Generated by Django 5.2.15 on 2026-08-02 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0028_inquiryproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentcalllog',
            name='classification_version',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='aiparsinglog',
            name='classification_version',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='classification_version',
            field=models.CharField(default='v1', max_length=10),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='product_match_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='product_match_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Product Matching Pending'), ('complete', 'Product Matching Complete'), ('error', 'Product Matching Error')], default='not_required', max_length=20),
        ),
        migrations.AddField(
            model_name='messageclassification',
            name='classification_version',
            field=models.CharField(default='v1', max_length=10),
        ),
        migrations.AlterField(
            model_name='agentcalllog',
            name='purpose',
            field=models.CharField(choices=[('classification', 'Inquiry Classification'), ('product_extraction', 'Product Extraction'), ('match_verification', 'Inquiry Match Verification'), ('inquiry_extraction_v2', 'Inquiry Extraction V2'), ('inquiry_match_v2', 'Inquiry Match Decision V2')], db_index=True, max_length=50),
        ),
    ]
