# Generated by Django 5.2.15 on 2026-08-02 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0029_agentcalllog_classification_version_and_more'),
        ('whatsapp_bridge', '0026_whatsappaccount_classification_version_override'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiParseV2Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquiry_ids', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pass1_started', 'Pass 1 Started'), ('pass1_done', 'Pass 1 Done'), ('pass2_started', 'Pass 2 Started'), ('complete', 'Complete'), ('error', 'Error')], default='pass1_started', max_length=30)),
                ('pass1_request', models.JSONField(blank=True, null=True)),
                ('pass1_response', models.TextField(blank=True)),
                ('pass1_parsed', models.JSONField(blank=True, null=True)),
                ('pass2_request', models.JSONField(blank=True, null=True)),
                ('pass2_response', models.TextField(blank=True)),
                ('pass2_parsed', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_parse_v2_logs', to='whatsapp_bridge.whatsappaccount')),
                ('chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_parse_v2_logs', to='whatsapp_bridge.whatsappchat')),
                ('classification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_parse_v2_logs', to='trading.messageclassification')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_parse_v2_log', to='whatsapp_bridge.whatsappmessage')),
            ],
            options={
                'db_table': 'trading_ai_parse_v2_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['account', 'created_at'], name='trading_ai__account_cbe5ef_idx'), models.Index(fields=['status', 'created_at'], name='trading_ai__status_4ba724_idx')],
            },
        ),
    ]
