# Generated by Django 5.2.15 on 2026-08-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0031_add_non_aliases_to_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiparsev2log',
            name='candidate_search_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiparsev2log',
            name='pass1_ai_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiparsev2log',
            name='pass1_total_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiparsev2log',
            name='pass2_ai_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiparsev2log',
            name='pass2_total_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiparsev2log',
            name='total_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
