# Generated by Django 5.2.15 on 2026-08-04 14:58

from django.db import migrations, models


def backfill_product_tracking(apps, schema_editor):
    Product = apps.get_model('trading', 'Product')
    Product.objects.update(tracking=True)


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0032_aiparsev2log_candidate_search_ms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tracking',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(backfill_product_tracking, migrations.RunPython.noop),
    ]
