# Generated by Django 5.2.15 on 2026-08-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0034_update_match_v2_stock_status_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiryproduct',
            name='product_qty_at_match',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inquiryproduct',
            name='product_stock_status_at_match',
            field=models.CharField(choices=[('in_stock', 'In Stock'), ('out_of_stock', 'Out of Stock'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=20),
        ),
    ]
