# Generated by Django 5.2.15 on 2026-08-06 14:02

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0004_company_default_classification_version'),
        ('trading', '0036_update_v2_sku_extraction_prompt'),
        ('whatsapp_bridge', '0027_whatsappaccount_last_worker_heartbeat_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonInventoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_name', models.CharField(max_length=500)),
                ('normalized_name', models.CharField(blank=True, db_index=True, max_length=500)),
                ('normalized_key', models.CharField(blank=True, db_index=True, max_length=700)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('tracking', 'Tracking'), ('promoted_to_inventory', 'Promoted to Inventory'), ('dismissed', 'Dismissed'), ('merged', 'Merged')], db_index=True, default='tracking', max_length=30)),
                ('mention_count', models.PositiveIntegerField(default=0)),
                ('buy_mention_count', models.PositiveIntegerField(default=0)),
                ('sell_mention_count', models.PositiveIntegerField(default=0)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=512, null=True)),
                ('embedding_model', models.CharField(blank=True, max_length=255)),
                ('embedding_metadata', models.JSONField(blank=True, null=True)),
                ('embedding_status', models.CharField(choices=[('pending', 'Pending'), ('embedded', 'Embedded'), ('error', 'Error'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=20)),
                ('embedding_error', models.TextField(blank=True)),
                ('first_seen_at', models.DateTimeField(db_index=True)),
                ('last_seen_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_inventory_products', to='tenancy.company')),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_products', to='trading.noninventoryproduct')),
                ('promoted_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='non_inventory_sources', to='trading.product')),
            ],
            options={
                'db_table': 'trading_non_inventory_product',
                'ordering': ['-last_seen_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='NonInventoryProductMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquiry_type', models.CharField(db_index=True, max_length=10)),
                ('source_product_index', models.PositiveIntegerField(blank=True, null=True)),
                ('raw_text', models.TextField(blank=True)),
                ('canonical_name_from_ai', models.CharField(max_length=500)),
                ('normalized_name_from_ai', models.CharField(blank=True, db_index=True, max_length=500)),
                ('brand_from_ai', models.CharField(blank=True, max_length=100)),
                ('attributes_from_ai', models.JSONField(blank=True, default=dict)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('match_source', models.CharField(blank=True, choices=[('deterministic', 'Deterministic'), ('embedding', 'Embedding'), ('ai', 'AI'), ('manual', 'Manual')], db_index=True, max_length=30)),
                ('match_confidence', models.FloatField(blank=True, null=True)),
                ('match_reason', models.TextField(blank=True)),
                ('message_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='non_inventory_product_mentions', to='whatsapp_bridge.whatsappaccount')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_inventory_product_mentions', to='tenancy.company')),
                ('company_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='non_inventory_product_mentions', to='tenancy.companycontact')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='non_inventory_product_mentions', to='whatsapp_bridge.whatsappcontact')),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_inventory_mentions', to='trading.inquiry')),
                ('inquiry_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='non_inventory_mentions', to='trading.inquiryproduct')),
                ('non_inventory_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='trading.noninventoryproduct')),
                ('source_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='non_inventory_product_mentions', to='whatsapp_bridge.whatsappmessage')),
            ],
            options={
                'db_table': 'trading_non_inventory_product_mention',
                'ordering': ['-message_time', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='noninventoryproduct',
            index=models.Index(fields=['company', 'status', 'last_seen_at'], name='noninv_company_status_seen_idx'),
        ),
        migrations.AddIndex(
            model_name='noninventoryproduct',
            index=models.Index(fields=['company', 'brand', 'normalized_name'], name='noninv_company_brand_name_idx'),
        ),
        migrations.AddIndex(
            model_name='noninventoryproduct',
            index=models.Index(fields=['promoted_product'], name='noninv_promoted_product_idx'),
        ),
        migrations.AddIndex(
            model_name='noninventoryproduct',
            index=models.Index(fields=['merged_into'], name='noninv_merged_into_idx'),
        ),
        migrations.AddConstraint(
            model_name='noninventoryproduct',
            constraint=models.UniqueConstraint(condition=models.Q(('normalized_key', ''), _negated=True), fields=('company', 'normalized_key'), name='uniq_noninv_company_norm_key'),
        ),
        migrations.AddIndex(
            model_name='noninventoryproductmention',
            index=models.Index(fields=['company', 'inquiry_type', 'message_time'], name='noninvm_cmp_type_time_idx'),
        ),
        migrations.AddIndex(
            model_name='noninventoryproductmention',
            index=models.Index(fields=['non_inventory_product', 'inquiry_type', 'message_time'], name='noninvm_prod_type_time_idx'),
        ),
        migrations.AddIndex(
            model_name='noninventoryproductmention',
            index=models.Index(fields=['company', 'match_source'], name='noninvmen_company_source_idx'),
        ),
        migrations.AddConstraint(
            model_name='noninventoryproductmention',
            constraint=models.UniqueConstraint(condition=models.Q(('inquiry_product__isnull', False)), fields=('company', 'inquiry_product'), name='uniq_noninv_mention_inq_product'),
        ),
    ]
