# Generated by Django 5.2.15 on 2026-08-22 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0005_company_ai_parsing_enabled'),
        ('trading', '0042_selling_offer_format_options'),
        ('whatsapp_bridge', '0027_whatsappaccount_last_worker_heartbeat_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='V2MatchTrainingSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_index', models.PositiveIntegerField()),
                ('query_text', models.TextField(blank=True)),
                ('candidates', models.JSONField(default=list)),
                ('ai_product_id', models.PositiveIntegerField(blank=True, null=True)),
                ('ai_match_type', models.CharField(blank=True, max_length=20)),
                ('best_distance', models.FloatField(blank=True, null=True)),
                ('correct_distance', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='v2_match_training_samples', to='tenancy.company')),
                ('correct_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='trading.product')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='v2_match_training_samples', to='whatsapp_bridge.whatsappmessage')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trading_v2_match_training_sample',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('message', 'line_index'), name='unique_v2_training_sample_line')],
            },
        ),
    ]
