# Generated by Django 5.2.15 on 2026-09-12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_providers', '0010_default_agent_target'),
        ('trading', '0044_automatedpricecapture_failure_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptconfig',
            name='kiwi_router',
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={'capability': 'agent'},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='prompt_configs',
                to='ai_providers.kiwirouter',
            ),
        ),
    ]
