# Generated by Django 5.2.15 on 2026-09-28 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0006_company_enforce_validity_period'),
        ('trading', '0057_agent_call_log_company'),
        ('whatsapp_bridge', '0033_whatsappcontact_is_existing_chat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InquiryForwardingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquiry_type', models.CharField(choices=[('buy', 'WTB'), ('sell', 'WTS')], max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=False)),
                ('include_original_message', models.BooleanField(default=True)),
                ('include_stock_suggestions', models.BooleanField(default=True)),
                ('include_sender_link', models.BooleanField(default=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('forwarded_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiry_forwarding_rules', to='tenancy.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiry_forwarding_rules_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trading_inquiry_forwarding_rule',
                'ordering': ['inquiry_type'],
            },
        ),
        migrations.CreateModel(
            name='InquiryForwardingExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exclusion_type', models.CharField(choices=[('contact', 'Source contact'), ('group', 'Source group')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='whatsapp_bridge.whatsappcontact')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='whatsapp_bridge.whatsappgroup')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusions', to='trading.inquiryforwardingrule')),
            ],
            options={
                'db_table': 'trading_inquiry_forwarding_exclusion',
            },
        ),
        migrations.CreateModel(
            name='InquiryForwardingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('skipped', 'Skipped'), ('partial', 'Partial'), ('complete', 'Complete'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=120)),
                ('message_snapshot', models.TextField(blank=True)),
                ('destination_count', models.PositiveIntegerField(default=0)),
                ('queued_count', models.PositiveIntegerField(default=0)),
                ('blocked_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forwarding_runs', to='trading.inquiry')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='trading.inquiryforwardingrule')),
                ('source_message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='whatsapp_bridge.whatsappmessage')),
            ],
            options={
                'db_table': 'trading_inquiry_forwarding_run',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InquiryForwardingTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('contact', 'Direct contact'), ('group', 'Group')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='whatsapp_bridge.whatsappcontact')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='whatsapp_bridge.whatsappgroup')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='trading.inquiryforwardingrule')),
            ],
            options={
                'db_table': 'trading_inquiry_forwarding_target',
            },
        ),
        migrations.CreateModel(
            name='InquiryForwardingDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
                ('reason', models.CharField(blank=True, max_length=120)),
                ('destination_label', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('outbound_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiry_forwarding_deliveries', to='whatsapp_bridge.outboundmessage')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='trading.inquiryforwardingrun')),
                ('target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='trading.inquiryforwardingtarget')),
            ],
            options={
                'db_table': 'trading_inquiry_forwarding_delivery',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='inquiryforwardingrule',
            constraint=models.UniqueConstraint(fields=('company', 'inquiry_type'), name='unique_company_inquiry_forwarding_type'),
        ),
        migrations.AddConstraint(
            model_name='inquiryforwardingexclusion',
            constraint=models.UniqueConstraint(fields=('rule', 'contact'), name='unique_forward_exclusion_contact'),
        ),
        migrations.AddConstraint(
            model_name='inquiryforwardingexclusion',
            constraint=models.UniqueConstraint(fields=('rule', 'group'), name='unique_forward_exclusion_group'),
        ),
        migrations.AddConstraint(
            model_name='inquiryforwardingexclusion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('contact__isnull', False), ('exclusion_type', 'contact'), ('group__isnull', True)), models.Q(('contact__isnull', True), ('exclusion_type', 'group'), ('group__isnull', False)), _connector='OR'), name='valid_forward_exclusion_endpoint'),
        ),
        migrations.AddConstraint(
            model_name='inquiryforwardingrun',
            constraint=models.UniqueConstraint(fields=('rule', 'inquiry'), name='unique_forward_rule_inquiry'),
        ),
        migrations.AddConstraint(
            model_name='inquiryforwardingtarget',
            constraint=models.UniqueConstraint(fields=('rule', 'contact'), name='unique_forward_rule_contact'),
        ),
        migrations.AddConstraint(
            model_name='inquiryforwardingtarget',
            constraint=models.UniqueConstraint(fields=('rule', 'group'), name='unique_forward_rule_group'),
        ),
        migrations.AddConstraint(
            model_name='inquiryforwardingtarget',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('contact__isnull', False), ('group__isnull', True), ('target_type', 'contact')), models.Q(('contact__isnull', True), ('group__isnull', False), ('target_type', 'group')), _connector='OR'), name='valid_forward_target_endpoint'),
        ),
        migrations.AddConstraint(
            model_name='inquiryforwardingdelivery',
            constraint=models.UniqueConstraint(fields=('run', 'target'), name='unique_forward_run_target'),
        ),
    ]
