# Generated by Django 5.2.15 on 2026-09-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0058_inquiryforwardingrule_inquiryforwardingexclusion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiryforwardingrule',
            name='include_inquiry_id',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inquiryforwardingrule',
            name='include_summary',
            field=models.BooleanField(default=True),
        ),
    ]
