# Generated by Django 5.2.15 on 2026-09-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0059_inquiryforwardingrule_include_inquiry_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiryforwardingrule',
            name='prefill_sender_link_products',
            field=models.BooleanField(default=True),
        ),
    ]
