# Generated by Django 5.2.15 on 2026-09-30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0060_inquiryforwardingrule_prefill_sender_link_products'),
        ('whatsapp_bridge', '0032_outbound_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyinginquiry',
            name='image_asset',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='buying_campaigns',
                to='whatsapp_bridge.outboundasset',
            ),
        ),
        migrations.AddField(
            model_name='sellingoffer',
            name='image_asset',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='selling_campaigns',
                to='whatsapp_bridge.outboundasset',
            ),
        ),
    ]
