const pageDescriptions = {
  sessions: 'Connect and manage WhatsApp communication accounts.',
  conversations: 'Read, search, and respond to WhatsApp conversations.',
  activity: 'Review session, ingestion, and system activity.',
  storage: 'Monitor stored media and manage retention.',
  'message-logs': 'Inspect message ingestion and processing records.',
  'ai-providers': 'Configure company AI agents, models, and routing targets.',
  'dropped-messages': 'Review messages excluded before downstream processing.',
  'worker-alerts': 'Investigate background worker health and alerts.',
  'baileys-events': 'Inspect WhatsApp worker connection events.',
  'stuck-receipts': 'Resolve delivery receipts awaiting completion.',
  'unresolved-messages': 'Review messages requiring manual resolution.',
  'message-trace': 'Trace a message through ingestion and processing.',
  'ai-parsing-log': 'Inspect legacy AI parsing requests and results.',
  'ai-parse-v2-log': 'Inspect V2 gate, extraction, and matching passes.',
  contacts: 'Browse contacts available to this workspace.',
  groups: 'Browse synced groups and current send eligibility.',
  trading: 'Live inquiry classification and stock matching.',
  'selling-offers': 'Build and send direct selling campaigns.',
  'trading-analytics': 'Measure inquiry volume, outcomes, and response performance.',
  'report-summary': 'Review consolidated operational reporting.',
  'inventory-product-mentions': 'Analyze inquiry activity for inventory products.',
  'selling-offers-report': 'Review selling campaign delivery and engagement.',
  inquiries: 'Review classified buying and selling inquiries.',
  'inquiry-products': 'Audit products extracted from inquiry messages.',
  'non-inventory-products': 'Maintain trusted products outside current inventory.',
  products: 'Maintain inventory, pricing, aliases, and product attributes.',
  'v2-candidate-search': 'Test and inspect inventory matching candidates.',
  'product-price-update': 'Review automated inventory update activity.',
  'buying-inquiries': 'Build and send direct buying campaigns.',
  'group-buying-inquiries': 'Send buying campaigns to eligible groups.',
  'group-selling-offers': 'Send selling campaigns to eligible groups.',
  'ai-instructions': 'Configure company AI instructions and execution targets.',
  'v2-settings': 'Configure V2 classification and GatePass behavior.',
  'tenant-admin': 'Create and manage company workspaces.',
  'v2-match-training': 'Review and correct V2 product matches.',
  'task-operations': 'Monitor queues, workers, schedules, and task execution.',
  'task-queues': 'Configure queue concurrency, modes, and timeouts.',
  'kiwi-router': 'Route AI work across ordered provider agents.',
  'inquiry-forwarding': 'Configure strict WTB and WTS forwarding rules.',
  'company-users': 'Manage workspace users and memberships.',
  'company-roles': 'Configure role permissions and access boundaries.',
  clientpulse: 'Maintain customer relationships and follow-up context.',
  'clientpulse-profile': 'Review customer details, activity, and conversations.',
  'clientpulse-settings': 'Configure ClientPulse automation and policies.',
  'clientpulse-reminders': 'Plan and track customer follow-up reminders.',
}

export function pageDescription(routeName) {
  return pageDescriptions[routeName] || 'Manage the current ChatLens workspace.'
}
