# Generated by Django 5.2.15 on 2026-07-22 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('signal', 'Signal'), ('discord', 'Discord'), ('gmail', 'Gmail'), ('exchange', 'Exchange'), ('imap', 'IMAP'), ('other', 'Other')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('external_account_id', models.CharField(blank=True, max_length=255)),
                ('config', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tenant_communication_account',
                'ordering': ['company__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AccountEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint_type', models.CharField(choices=[('phone', 'Phone'), ('email', 'Email'), ('handle', 'Handle / Username'), ('device', 'Device Session')], max_length=20)),
                ('value', models.CharField(max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('communication_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='tenancy.communicationaccount')),
            ],
            options={
                'db_table': 'tenant_account_endpoint',
                'ordering': ['communication_account__name', '-is_primary', 'value'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('company_type', models.CharField(choices=[('control', 'Control'), ('customer', 'Customer Company'), ('internal', 'Internal')], default='customer', max_length=20)),
                ('industry_type', models.CharField(choices=[('general', 'General'), ('trading', 'Trading'), ('real_estate', 'Real Estate')], default='general', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_companies', to='tenancy.company')),
            ],
            options={
                'db_table': 'tenant_company',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='communicationaccount',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_accounts', to='tenancy.company'),
        ),
        migrations.CreateModel(
            name='CompanyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(blank=True, choices=[('supplier', 'Supplier'), ('customer', 'Customer'), ('both', 'Both'), ('other', 'Other')], max_length=20)),
                ('is_company', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='tenancy.company')),
            ],
            options={
                'db_table': 'tenant_company_contact',
                'ordering': ['company__name', 'display_name', 'legal_name'],
            },
        ),
        migrations.CreateModel(
            name='ConnectionProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('signal', 'Signal'), ('discord', 'Discord'), ('gmail', 'Gmail'), ('exchange', 'Exchange'), ('imap', 'IMAP'), ('other', 'Other')], max_length=20)),
                ('provider_type', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default_for_channel', models.BooleanField(default=False)),
                ('capabilities', models.JSONField(blank=True, default=list)),
                ('config_schema', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tenant_connection_provider',
                'ordering': ['channel', 'name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default_for_channel', True)), fields=('channel',), name='unique_default_provider_per_channel')],
            },
        ),
        migrations.AddField(
            model_name='communicationaccount',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='communication_accounts', to='tenancy.connectionprovider'),
        ),
        migrations.CreateModel(
            name='CompanyContactIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_type', models.CharField(choices=[('phone', 'Phone'), ('email', 'Email'), ('whatsapp_jid', 'WhatsApp JID'), ('telegram_handle', 'Telegram Handle'), ('discord_handle', 'Discord Handle'), ('other', 'Other')], max_length=30)),
                ('value', models.CharField(max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identities', to='tenancy.companycontact')),
            ],
            options={
                'db_table': 'tenant_company_contact_identity',
                'ordering': ['contact__company__name', 'contact__display_name', '-is_primary', 'value'],
                'constraints': [models.UniqueConstraint(fields=('contact', 'identity_type', 'value'), name='unique_company_contact_identity')],
            },
        ),
        migrations.CreateModel(
            name='CompanyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('super_user', 'Super User'), ('admin', 'Admin'), ('manager', 'Manager'), ('user', 'User'), ('viewer', 'Viewer')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenancy.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tenant_company_membership',
                'ordering': ['company__name', 'user__username'],
                'constraints': [models.UniqueConstraint(fields=('company', 'user'), name='unique_company_membership')],
            },
        ),
    ]
