# Generated by Django 5.2.15 on 2026-08-02 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0003_backfill_existing_tenant_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='default_classification_version',
            field=models.CharField(choices=[('v1', 'Classification V1'), ('v2', 'Classification V2')], default='v1', max_length=10),
        ),
    ]
