# Generated by Django 5.2.15 on 2026-10-01 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0007_company_ai_parsing_enabled_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=120, unique=True)),
                ('area', models.CharField(db_index=True, max_length=50)),
                ('label', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('supports_scope', models.BooleanField(default=False)),
                ('is_sensitive', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tenant_permission_definition',
                'ordering': ['area', 'code'],
            },
        ),
        migrations.AddField(
            model_name='companymembership',
            name='authorization_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='CompanyRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_system_role', models.BooleanField(default=False)),
                ('is_owner_role', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='tenancy.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_roles_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_roles_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tenant_company_role',
                'ordering': ['company__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AuthorizationAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=80)),
                ('before_snapshot', models.JSONField(blank=True, default=dict)),
                ('after_snapshot', models.JSONField(blank=True, default=dict)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('request_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorization_events_performed', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorization_events', to='tenancy.company')),
                ('target_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorization_events', to='tenancy.companymembership')),
                ('target_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorization_events', to='tenancy.companyrole')),
            ],
            options={
                'db_table': 'tenant_authorization_audit_event',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MembershipRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('legacy', 'Legacy role'), ('manual', 'Manual')], default='manual', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_role_assignments_created', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='tenancy.company')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='tenancy.companymembership')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_assignments', to='tenancy.companyrole')),
            ],
            options={
                'db_table': 'tenant_membership_role_assignment',
            },
        ),
        migrations.CreateModel(
            name='CompanyRolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_scope', models.CharField(choices=[('own', 'Own records'), ('assigned', 'Assigned records'), ('all', 'All company records')], default='all', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='tenancy.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_role_permissions_created', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_grants', to='tenancy.companyrole')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_grants', to='tenancy.permissiondefinition')),
            ],
            options={
                'db_table': 'tenant_company_role_permission',
            },
        ),
        migrations.AddConstraint(
            model_name='companyrole',
            constraint=models.UniqueConstraint(fields=('company', 'key'), name='unique_company_role_key'),
        ),
        migrations.AddConstraint(
            model_name='companyrole',
            constraint=models.UniqueConstraint(condition=models.Q(('is_owner_role', True)), fields=('company',), name='unique_company_owner_role'),
        ),
        migrations.AddIndex(
            model_name='authorizationauditevent',
            index=models.Index(fields=['company', 'created_at'], name='tenant_auth_company_2cf773_idx'),
        ),
        migrations.AddIndex(
            model_name='membershiproleassignment',
            index=models.Index(fields=['company', 'membership'], name='tenant_memb_company_c5cf01_idx'),
        ),
        migrations.AddConstraint(
            model_name='membershiproleassignment',
            constraint=models.UniqueConstraint(fields=('membership', 'role'), name='unique_membership_role_assignment'),
        ),
        migrations.AddIndex(
            model_name='companyrolepermission',
            index=models.Index(fields=['company', 'permission'], name='tenant_comp_company_bd3397_idx'),
        ),
        migrations.AddConstraint(
            model_name='companyrolepermission',
            constraint=models.UniqueConstraint(fields=('role', 'permission'), name='unique_company_role_permission'),
        ),
    ]
