# Generated by Django 5.2.15 on 2026-10-01 08:22

from django.db import migrations


CODES = [
    'conversations.chats.view', 'conversations.messages.view', 'conversations.messages.send',
    'conversations.contacts.update', 'conversations.accounts.manage', 'trading.board.view',
    'trading.inquiries.update', 'trading.matches.manage', 'trading.products.view',
    'trading.products.manage', 'trading.automation.manage', 'campaigns.campaigns.view',
    'campaigns.campaigns.create', 'campaigns.campaigns.update', 'campaigns.campaigns.delete',
    'campaigns.messages.send', 'campaigns.audiences.manage', 'clientpulse.clients.view',
    'clientpulse.clients.create', 'clientpulse.clients.update', 'clientpulse.clients.archive',
    'clientpulse.notes.manage', 'clientpulse.reminders.view', 'clientpulse.reminders.manage',
    'clientpulse.sequences.view', 'clientpulse.sequences.manage', 'clientpulse.messages.send_manual',
    'clientpulse.messages.send_automated', 'clientpulse.contacts.merge', 'clientpulse.consent.manage',
    'clientpulse.reports.view', 'clientpulse.data.export', 'integrations.connections.view',
    'integrations.connections.manage', 'integrations.sync.execute', 'integrations.sync.view_history',
    'integrations.conflicts.resolve', 'reports.company.view', 'reports.company.export',
    'tasks.company.view', 'tasks.company.retry', 'settings.company.view', 'settings.company.manage',
    'users.memberships.view', 'users.memberships.manage', 'users.roles.view',
    'users.roles.manage', 'sending.policy.manage', 'automation.company.enable',
]
SCOPED = {
    'conversations.chats.view', 'conversations.messages.view', 'conversations.messages.send',
    'conversations.contacts.update', 'clientpulse.clients.view', 'clientpulse.clients.update',
    'clientpulse.clients.archive', 'clientpulse.notes.manage', 'clientpulse.reminders.view',
    'clientpulse.reminders.manage', 'clientpulse.messages.send_manual',
    'clientpulse.consent.manage', 'clientpulse.reports.view',
}
SENSITIVE = {
    code for code in CODES if code.endswith(('.manage', '.send', '.export', '.retry'))
} | {
    'clientpulse.messages.send_manual', 'clientpulse.messages.send_automated',
    'clientpulse.contacts.merge', 'integrations.sync.execute', 'automation.company.enable',
}
ROLE_NAMES = {
    'super_user': 'Owner', 'admin': 'Administrator', 'manager': 'Manager',
    'user': 'Sales Agent', 'viewer': 'Viewer', 'campaign_operator': 'Campaign Operator',
    'integration_manager': 'Integration Manager',
}


def grants_for(role):
    if role in {'super_user', 'admin'}:
        return set(CODES)
    if role == 'manager':
        return {
            code for code in CODES
            if not code.startswith(('users.', 'integrations.', 'settings.', 'sending.'))
            and code not in {'automation.company.enable', 'clientpulse.messages.send_automated', 'tasks.company.retry'}
        }
    if role == 'user':
        return {
            'conversations.chats.view', 'conversations.messages.view', 'conversations.messages.send',
            'conversations.contacts.update', 'trading.board.view', 'trading.inquiries.update',
            'trading.products.view', 'campaigns.campaigns.view', 'clientpulse.clients.view',
            'clientpulse.clients.update', 'clientpulse.notes.manage', 'clientpulse.reminders.view',
            'clientpulse.reminders.manage', 'clientpulse.sequences.view',
            'clientpulse.messages.send_manual', 'clientpulse.reports.view', 'reports.company.view',
        }
    if role == 'viewer':
        return {code for code in CODES if code.endswith(('.view', '.view_history'))}
    if role == 'campaign_operator':
        return {code for code in CODES if code.startswith('campaigns.')} | {
            'trading.products.view', 'conversations.chats.view',
            'conversations.messages.send', 'reports.company.view',
        }
    return {code for code in CODES if code.startswith('integrations.')} | {'tasks.company.view'}


def seed_rbac(apps, schema_editor):
    Company = apps.get_model('tenancy', 'Company')
    Membership = apps.get_model('tenancy', 'CompanyMembership')
    Permission = apps.get_model('tenancy', 'PermissionDefinition')
    Role = apps.get_model('tenancy', 'CompanyRole')
    Grant = apps.get_model('tenancy', 'CompanyRolePermission')
    Assignment = apps.get_model('tenancy', 'MembershipRoleAssignment')

    definitions = {}
    for code in CODES:
        area, resource, action = code.split('.', 2)
        definitions[code] = Permission.objects.create(
            code=code,
            area=area,
            label=f'{resource.replace("_", " ").title()}: {action.replace("_", " ").title()}',
            supports_scope=code in SCOPED,
            is_sensitive=code in SENSITIVE,
        )
    for company in Company.objects.all().iterator():
        roles = {}
        for key, name in ROLE_NAMES.items():
            role = Role.objects.create(
                company=company, key=key, name=name, is_system_role=True,
                is_owner_role=key == 'super_user',
            )
            roles[key] = role
            Grant.objects.bulk_create([
                Grant(
                    company=company, role=role, permission=definitions[code],
                    record_scope='assigned' if key == 'user' and code in SCOPED else 'all',
                )
                for code in grants_for(key)
            ])
        Assignment.objects.bulk_create([
            Assignment(
                company=membership.company,
                membership=membership,
                role=roles[membership.role],
                source='legacy',
            )
            for membership in Membership.objects.filter(company=company)
        ])


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0008_permissiondefinition_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_rbac, migrations.RunPython.noop),
    ]
