# Generated by Django 5.2.15 on 2026-06-23 17:26

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('whatsapp_bridge', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql='CREATE EXTENSION IF NOT EXISTS vector;',
            reverse_sql='DROP EXTENSION IF EXISTS vector;',
        ),
        migrations.CreateModel(
            name='MessageAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, max_length=20)),
                ('sentiment', models.CharField(blank=True, choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], max_length=50)),
                ('intent', models.CharField(choices=[('price_inquiry', 'Price Inquiry'), ('stock_inquiry', 'Stock Inquiry'), ('order_request', 'Order Request'), ('invoice_request', 'Invoice Request'), ('payment_followup', 'Payment Follow-up'), ('delivery_followup', 'Delivery Follow-up'), ('warranty_complaint', 'Warranty Complaint'), ('general_complaint', 'General Complaint'), ('greeting', 'Greeting'), ('unknown', 'Unknown')], default='unknown', max_length=100)),
                ('urgency_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lead_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('product_mentions', models.JSONField(blank=True, null=True)),
                ('extracted_entities', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='whatsapp_bridge.whatsappmessage')),
            ],
            options={
                'db_table': 'message_analysis',
            },
        ),
        migrations.CreateModel(
            name='MessageEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('embedding_model', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='whatsapp_bridge.whatsappmessage')),
            ],
            options={
                'db_table': 'message_embedding',
            },
        ),
    ]
