# Generated by Django 5.2.15 on 2026-07-13 22:19

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_intelligence', '0005_product_embedding_vector_index'),
        ('trading', '0015_productalias'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAliasEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=512, null=True)),
                ('embedding_model', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alias', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='trading.productalias')),
            ],
            options={
                'db_table': 'product_alias_embedding',
            },
        ),
    ]
