# Generated by Django 5.2.15 on 2026-07-14 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_providers', '0003_alter_aiproviderconfig_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProviderRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokens', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_log', to='ai_providers.aiproviderconfig')),
            ],
        ),
    ]
