# Generated by Django 5.2.15 on 2026-08-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_providers', '0005_update_deepseek_v4_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiproviderconfig',
            name='provider',
            field=models.CharField(choices=[('voyage', 'Voyage AI'), ('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('google', 'Google Gemini'), ('deepseek', 'DeepSeek'), ('qwen', 'Qwen (Alibaba)'), ('kimi', 'Kimi (Moonshot)'), ('groq', 'Groq'), ('mistral', 'Mistral AI'), ('grok', 'Grok (xAI)'), ('perplexity', 'Perplexity'), ('together', 'Together AI'), ('cohere', 'Cohere'), ('jina', 'Jina AI'), ('lm_studio', 'LM Studio Local'), ('other', 'Other')], max_length=50),
        ),
    ]
