# Generated by Django 5.2.15 on 2026-09-10 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_providers', '0008_add_openrouter_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='KiwiRouter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('capability', models.CharField(choices=[('embedding', 'Embeddings'), ('chat', 'Chat / Completion'), ('agent', 'General AI Agent')], max_length=50)),
                ('strategy', models.CharField(choices=[('ordered_capacity_fill', 'Ordered capacity fill')], default='ordered_capacity_fill', max_length=50)),
                ('default_request_timeout_seconds', models.PositiveIntegerField(default=60)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='KiwiRouterMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveIntegerField()),
                ('is_enabled', models.BooleanField(default=True)),
                ('rpm_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('tpm_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('max_concurrency', models.PositiveIntegerField(blank=True, null=True)),
                ('input_cost_per_million', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('output_cost_per_million', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('metadata_source', models.CharField(choices=[('provider_published', 'Provider published'), ('operator_supplied', 'Operator supplied'), ('incomplete', 'Incomplete')], default='incomplete', max_length=30)),
                ('metadata_verified_at', models.DateTimeField(blank=True, null=True)),
                ('metadata_review_due_at', models.DateTimeField(blank=True, null=True)),
                ('request_timeout_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kiwi_router_members', to='ai_providers.aiproviderconfig')),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='ai_providers.kiwirouter')),
            ],
            options={
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='KiwiRouterReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlation_id', models.CharField(db_index=True, max_length=255)),
                ('task_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('estimated_input_tokens', models.PositiveIntegerField(default=0)),
                ('estimated_output_tokens', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('dispatched', 'Dispatched'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('expired', 'Expired')], default='reserved', max_length=20)),
                ('reserved_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='ai_providers.kiwiroutermember')),
            ],
        ),
        migrations.CreateModel(
            name='KiwiRoutingDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('correlation_id', models.CharField(db_index=True, max_length=255)),
                ('workflow_key', models.CharField(max_length=100)),
                ('strategy', models.CharField(max_length=50)),
                ('decision', models.CharField(choices=[('selected', 'Selected'), ('deferred', 'Deferred'), ('skipped', 'Skipped')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('estimated_input_tokens', models.PositiveIntegerField(default=0)),
                ('estimated_output_tokens', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to='ai_providers.kiwiroutermember')),
                ('provider_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kiwi_routing_decisions', to='ai_providers.aiproviderconfig')),
                ('router', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to='ai_providers.kiwirouter')),
            ],
        ),
        migrations.AddConstraint(
            model_name='kiwiroutermember',
            constraint=models.UniqueConstraint(fields=('router', 'priority'), name='unique_kiwi_router_priority'),
        ),
        migrations.AddIndex(
            model_name='kiwirouterreservation',
            index=models.Index(fields=['member', 'reserved_at'], name='ai_provider_member__1738f5_idx'),
        ),
    ]
