# Generated by Django 5.2.15 on 2026-09-12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_providers', '0009_add_kiwi_router'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultAgentTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kiwi_router', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_agent_targets', to='ai_providers.kiwirouter')),
            ],
        ),
    ]
