<script setup>
import { computed, onMounted, reactive, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { clientPulseApi } from '@/api'
import { useAuthStore } from '@/stores/auth.js'
import ClientPulseFollowUpComposer from '@/components/ClientPulseFollowUpComposer.vue'
import '@/assets/clientpulse.css'

const route = useRoute(), router = useRouter(), auth = useAuthStore()
const id = Number(route.params.id), client = ref(null), notes = ref([]), timeline = ref([]), consents = ref([]), tags = ref([]), owners = ref([])
const loading = ref(true), busy = ref(''), error = ref(''), success = ref('')
const canEdit = computed(() => auth.hasPermission('clientpulse.clients.update'))
const canNotes = computed(() => auth.hasPermission('clientpulse.notes.manage'))
const canConsent = computed(() => auth.hasPermission('clientpulse.consent.manage'))
const form = reactive({ display_name:'', legal_name:'', contact_type:'person', lifecycle_stage:'lead', priority:'normal', source:'manual', owner_id:null, preferred_channel:'', preferred_language:'', timezone:'Asia/Dubai', do_not_contact:false, do_not_contact_reason:'', tag_ids:[] })
const identity = reactive({ identity_type:'phone', value:'', label:'' }), noteBody = ref('')
const consent = reactive({ channel:'whatsapp', purpose:'follow_up', status:'unknown', source:'manual' })
const newTag = ref('')
function message(exc, fallback) { const data=exc.response?.data; return data?.detail || (data ? JSON.stringify(data) : fallback) }
function syncForm() { const c=client.value; Object.assign(form,{ display_name:c.display_name||'',legal_name:c.legal_name||'',contact_type:c.contact_type,lifecycle_stage:c.lifecycle_stage,priority:c.priority,source:c.source,owner_id:c.owner?.id||null,preferred_channel:c.preferred_channel||'',preferred_language:c.preferred_language||'',timezone:c.timezone||'Asia/Dubai',do_not_contact:c.do_not_contact,do_not_contact_reason:c.do_not_contact_reason||'',tag_ids:c.tags.map(t=>t.id) }) }
async function load() {
  loading.value=true; error.value=''
  try { const [c,n,t,co,ta,o]=await Promise.all([clientPulseApi.client(id),clientPulseApi.notes(id),clientPulseApi.timeline(id),clientPulseApi.consents(id),clientPulseApi.tags(),clientPulseApi.options()]); client.value=c.data;notes.value=n.data;timeline.value=t.data;consents.value=co.data;tags.value=ta.data;owners.value=o.data.owners;syncForm() }
  catch(exc){error.value=message(exc,'Unable to load client.')} finally{loading.value=false}
}
async function save(){busy.value='save';error.value='';success.value='';try{const{data}=await clientPulseApi.updateClient(id,{...form});client.value=data;syncForm();success.value='Client profile updated.';timeline.value=(await clientPulseApi.timeline(id)).data}catch(exc){error.value=message(exc,'Unable to update client.')}finally{busy.value=''}}
async function addIdentity(){busy.value='identity';try{await clientPulseApi.addIdentity(id,{...identity});Object.assign(identity,{identity_type:'phone',value:'',label:''});await load()}catch(exc){error.value=message(exc,'Unable to add identity.')}finally{busy.value=''}}
async function removeIdentity(item){if(!confirm(`Remove ${item.value}?`))return;await clientPulseApi.deleteIdentity(id,item.id);await load()}
async function addNote(){busy.value='note';try{await clientPulseApi.addNote(id,{body:noteBody.value});noteBody.value='';notes.value=(await clientPulseApi.notes(id)).data;timeline.value=(await clientPulseApi.timeline(id)).data}catch(exc){error.value=message(exc,'Unable to add note.')}finally{busy.value=''}}
async function saveConsent(){busy.value='consent';try{consents.value=(await clientPulseApi.saveConsent(id,{...consent})).data;timeline.value=(await clientPulseApi.timeline(id)).data}catch(exc){error.value=message(exc,'Unable to save consent.')}finally{busy.value=''}}
async function createTag(){if(!newTag.value.trim())return;try{await clientPulseApi.createTag({name:newTag.value});newTag.value='';tags.value=(await clientPulseApi.tags()).data}catch(exc){error.value=message(exc,'Unable to create tag.')}}
async function archive(){if(!confirm('Archive this client?'))return;await clientPulseApi.archiveClient(id);router.push('/clientpulse')}
async function followUpQueued(){timeline.value=(await clientPulseApi.timeline(id)).data}
onMounted(load)
</script>

<template><main class="cp-page"><div class="cp-shell"><RouterLink class="cp-back" to="/clientpulse">← Customer directory</RouterLink><div v-if="loading" class="cp-empty">Loading profile...</div><template v-else-if="client">
  <header class="cp-hero"><div><p class="cp-eyebrow">Client profile</p><h1 class="cp-title">{{ client.display_name || client.legal_name }}</h1><p class="cp-muted">#{{ client.id }} · {{ client.lifecycle_stage.replaceAll('_',' ') }} · {{ client.owner?.user?.username || 'Unassigned' }}</p></div><button v-if="auth.hasPermission('clientpulse.clients.archive')" class="cp-button cp-danger" @click="archive">Archive</button></header>
  <p v-if="error" class="cp-notice error">{{ error }}</p><p v-if="success" class="cp-notice success">{{ success }}</p>
  <div v-if="canEdit" class="cp-actions"><input v-model="newTag" class="cp-input" placeholder="Create a reusable tag" /><button type="button" class="cp-button" @click="createTag">Add tag</button></div>
  <div v-if="auth.hasPermission('clientpulse.reminders.manage')" class="cp-actions"><RouterLink class="cp-button cp-primary" :to="`/clientpulse-reminders?profile_id=${id}&create=1`">Create reminder</RouterLink></div>
  <ClientPulseFollowUpComposer v-if="auth.hasPermission('clientpulse.messages.send_manual')" :client="client" style="margin-top:16px" @queued="followUpQueued" />
  <div class="cp-cards"><section class="cp-panel cp-card"><h2>Relationship profile</h2><form class="cp-form-grid" @submit.prevent="save"><label>Name<input v-model="form.display_name" class="cp-input" :disabled="!canEdit" /></label><label>Legal name<input v-model="form.legal_name" class="cp-input" :disabled="!canEdit" /></label><label>Type<select v-model="form.contact_type" class="cp-select" :disabled="!canEdit"><option value="person">Person</option><option value="organization">Organization</option></select></label><label>Lifecycle<select v-model="form.lifecycle_stage" class="cp-select" :disabled="!canEdit"><option v-for="v in ['lead','prospect','active_customer','dormant','lost','blocked']" :key="v" :value="v">{{ v.replaceAll('_',' ') }}</option></select></label><label>Priority<select v-model="form.priority" class="cp-select" :disabled="!canEdit"><option v-for="v in ['low','normal','high','critical']" :key="v">{{ v }}</option></select></label><label>Owner<select v-model="form.owner_id" class="cp-select" :disabled="!canEdit"><option :value="null">Unassigned</option><option v-for="owner in owners" :key="owner.id" :value="owner.id">{{ owner.username }}</option></select></label><label>Preferred channel<select v-model="form.preferred_channel" class="cp-select" :disabled="!canEdit"><option value="">Not set</option><option v-for="v in ['whatsapp','email','phone','other']" :key="v">{{ v }}</option></select></label><label>Language<input v-model="form.preferred_language" class="cp-input" :disabled="!canEdit" /></label><label>Timezone<input v-model="form.timezone" class="cp-input" :disabled="!canEdit" /></label><div class="wide"><strong>Tags</strong><div class="cp-checks"><label v-for="tag in tags" :key="tag.id"><input v-model="form.tag_ids" type="checkbox" :value="tag.id" :disabled="!canEdit" />{{ tag.name }}</label></div></div><label class="wide"><span><input v-model="form.do_not_contact" type="checkbox" :disabled="!canEdit" /> Do not contact</span><textarea v-if="form.do_not_contact" v-model="form.do_not_contact_reason" class="cp-textarea" placeholder="Required reason" /></label><div v-if="canEdit" class="cp-actions wide"><button class="cp-button cp-primary" :disabled="busy==='save'">{{ busy==='save'?'Saving...':'Save profile' }}</button></div></form></section>
  <section class="cp-panel cp-card"><h2>Contact identities</h2><div class="cp-list"><div v-for="item in client.identities" :key="item.id" class="cp-item"><strong>{{ item.value }}</strong><p class="cp-muted">{{ item.identity_type }} {{ item.label }}</p><button v-if="canEdit" class="cp-button cp-danger" @click="removeIdentity(item)">Remove</button></div><div v-for="item in client.whatsapp_contacts" :key="`wa-${item.id}`" class="cp-item"><strong>{{ item.display_name || item.phone_number }}</strong><p class="cp-muted">Linked WhatsApp · {{ item.account_name }}</p></div></div><form v-if="canEdit" class="cp-form-grid" style="margin-top:12px" @submit.prevent="addIdentity"><label>Type<select v-model="identity.identity_type" class="cp-select"><option value="phone">Phone</option><option value="email">Email</option><option value="whatsapp_jid">WhatsApp JID</option></select></label><label>Value<input v-model="identity.value" class="cp-input" required /></label><label>Label<input v-model="identity.label" class="cp-input" /></label><div class="cp-actions wide"><button class="cp-button cp-primary">Add identity</button></div></form></section></div>
  <div class="cp-cards"><section class="cp-panel cp-card"><h2>Notes</h2><form v-if="canNotes" @submit.prevent="addNote"><textarea v-model="noteBody" class="cp-textarea" placeholder="Add relationship context..." required></textarea><div class="cp-actions"><button class="cp-button cp-primary">Add note</button></div></form><div class="cp-list"><article v-for="note in notes" :key="note.id" class="cp-item"><p>{{ note.body }}</p><small class="cp-muted">{{ note.created_by?.username }} · {{ new Date(note.created_at).toLocaleString() }}</small></article><p v-if="!notes.length" class="cp-empty">No notes yet.</p></div></section>
  <section class="cp-panel cp-card"><h2>Consent</h2><form v-if="canConsent" class="cp-form-grid" @submit.prevent="saveConsent"><label>Channel<select v-model="consent.channel" class="cp-select"><option value="whatsapp">WhatsApp</option><option value="email">Email</option><option value="phone">Phone</option></select></label><label>Purpose<select v-model="consent.purpose" class="cp-select"><option value="transactional">Transactional</option><option value="follow_up">Follow-up</option><option value="marketing">Marketing</option></select></label><label>Status<select v-model="consent.status" class="cp-select"><option v-for="v in ['unknown','granted','denied','revoked']" :key="v">{{ v }}</option></select></label><div class="cp-actions wide"><button class="cp-button cp-primary">Save consent</button></div></form><div class="cp-list"><div v-for="item in consents" :key="item.id" class="cp-item"><strong>{{ item.channel }} · {{ item.purpose }}</strong><p><span class="cp-badge">{{ item.status }}</span></p></div><p v-if="!consents.length" class="cp-empty">No consent records.</p></div></section></div>
  <section class="cp-panel cp-card" style="margin-top:16px"><h2>Activity timeline</h2><div class="cp-list"><article v-for="item in timeline" :key="item.id" class="cp-item"><strong>{{ item.title }}</strong><span v-if="item.outbound" class="cp-badge" :class="`status-${item.outbound.status}`">{{ item.outbound.status.replaceAll('_',' ') }}</span><p v-if="item.summary">{{ item.summary }}</p><p v-if="item.outbound" class="cp-muted">{{ item.outbound.account_name }}<template v-if="item.outbound.status_reason"> · {{ item.outbound.status_reason }}</template></p><small class="cp-muted">{{ new Date(item.occurred_at).toLocaleString() }} · {{ item.created_by?.username || 'system' }}</small></article><p v-if="!timeline.length" class="cp-empty">No activity recorded.</p></div></section>
</template></div></main></template>
