# Generated by Django 5.2.15 on 2026-09-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_id', models.CharField(max_length=255, unique=True)),
                ('hostname', models.CharField(max_length=255)),
                ('process_id', models.PositiveIntegerField()),
                ('queue_names', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('starting', 'Starting'), ('running', 'Running'), ('stopping', 'Stopping'), ('stopped', 'Stopped'), ('unhealthy', 'Unhealthy')], default='starting', max_length=20)),
                ('version', models.CharField(blank=True, max_length=100)),
                ('started_at', models.DateTimeField()),
                ('last_heartbeat_at', models.DateTimeField()),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'queue_management_background_worker',
                'ordering': ['-last_heartbeat_at'],
            },
        ),
        migrations.CreateModel(
            name='QueueDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=150)),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_paused', models.BooleanField(default=False)),
                ('max_concurrency', models.PositiveIntegerField(default=1)),
                ('poll_interval_seconds', models.PositiveIntegerField(default=2)),
                ('lock_timeout_seconds', models.PositiveIntegerField(default=300)),
                ('default_max_attempts', models.PositiveIntegerField(default=3)),
                ('retry_backoff_base_seconds', models.PositiveIntegerField(default=15)),
                ('retry_backoff_max_seconds', models.PositiveIntegerField(default=900)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'queue_management_queue_definition',
                'ordering': ['name'],
            },
        ),
    ]
