<script setup>
defineProps({ open: { type: Boolean, default: false }, inquiry: { type: Object, default: null }, loading: { type: Boolean, default: false }, error: { type: String, default: '' }, lines: { type: Array, default: () => [] }, creatingIndex: { type: Number, default: null }, trackingIndex: { type: Number, default: null } })
defineEmits(['close', 'create-product', 'track-non-inventory'])

function formatAttributes(attributes) {
  if (!attributes || typeof attributes !== 'object' || Array.isArray(attributes)) return ''
  return Object.entries(attributes || {}).map(([key, value]) => `${key}: ${value}`).join(', ')
}
</script>

<template><Teleport to="#ui-teleport-host"><div v-if="open" class="backdrop" @click.self="$emit('close')"><section class="dialog" role="dialog" aria-modal="true"><header><div><strong>Inquiry Product List</strong><span>{{ inquiry?.summary || 'Parsed products from selected inquiry' }}</span></div><button type="button" @click="$emit('close')">×</button></header><div v-if="loading" class="state">Loading products...</div><div v-else-if="error" class="error">{{ error }}</div><div v-else-if="!lines.length" class="state">No product lines found.</div><div v-else class="list"><article v-for="line in lines" :key="line.index" :class="{ linked: line.has_inventory_mapping || line.inquiry_product_id }"><div class="main"><strong>{{ line.canonical_name || 'Invalid product line' }}</strong><div class="meta"><span v-if="line.brand">Brand {{ line.brand }}</span><span v-if="formatAttributes(line.attributes)">Attrs {{ formatAttributes(line.attributes) }}</span><span v-if="line.quantity">Qty {{ line.quantity }}</span><span v-if="line.price">{{ line.currency || '' }} {{ line.price }}</span><span v-if="line.match_type">AI match: {{ line.match_type }}</span></div><p v-if="line.product_name">Mapped to inventory: {{ line.product_name }}</p><p v-else-if="line.non_inventory_product_name">Tracked as non-inventory: {{ line.non_inventory_product_name }}</p><p v-else-if="line.inquiry_product_id">Inquiry product row already exists.</p></div><div class="actions"><span v-if="line.has_inventory_mapping || line.non_inventory_mention_id">Linked</span><button v-if="!line.has_inventory_mapping && !line.inquiry_product_id" type="button" :disabled="creatingIndex === line.index || !line.valid" @click="$emit('create-product', line)">{{ creatingIndex === line.index ? 'Creating...' : 'Create Product' }}</button><button v-if="line.can_track_non_inventory" type="button" :disabled="trackingIndex === line.index || !line.valid" @click="$emit('track-non-inventory', line)">{{ trackingIndex === line.index ? 'Tracking...' : 'Track Non-Inventory' }}</button></div></article></div></section></div></Teleport></template>

<style scoped>
.backdrop{position:fixed;z-index:1200;inset:0;display:grid;place-items:center;padding:20px;background:var(--ui-overlay)}.dialog{width:min(900px,96vw);max-height:88vh;overflow:auto;border:1px solid var(--ui-border);border-radius:var(--ui-radius-lg);background:var(--ui-surface);box-shadow:var(--ui-shadow-popover)}header{display:flex;align-items:center;justify-content:space-between;padding:14px 18px;border-bottom:1px solid var(--ui-border)}header strong,header span{display:block}header span{margin-top:3px;color:var(--ui-text-muted);font-size:.76rem}header button{border:0;background:transparent;color:var(--ui-text-muted);font-size:1.3rem;cursor:pointer}.state,.error{padding:28px;color:var(--ui-text-muted);text-align:center}.error{color:var(--ui-danger)}.list{padding:8px 18px 18px}.list article{display:flex;align-items:center;justify-content:space-between;gap:16px;padding:12px 0;border-bottom:1px solid var(--ui-border)}.list article.linked{background:linear-gradient(90deg,var(--ui-success-soft),transparent 35%)}.main{min-width:0}.main>strong{color:var(--ui-text-strong)}.meta{display:flex;flex-wrap:wrap;gap:8px;margin-top:4px;color:var(--ui-text-muted);font-size:.72rem}.main p{margin:5px 0 0;color:var(--ui-success);font-size:.75rem}.actions{display:flex;flex-shrink:0;align-items:center;gap:7px}.actions span{padding:3px 7px;border-radius:var(--ui-radius-pill);background:var(--ui-success-soft);color:var(--ui-success);font-size:.68rem;font-weight:800}.actions button{padding:6px 9px;border:1px solid var(--ui-primary);border-radius:var(--ui-radius-xs);background:var(--ui-primary);color:var(--ui-on-primary);cursor:pointer}.actions button+button{border-color:var(--ui-info);background:var(--ui-info)}.actions button:disabled{opacity:.5;cursor:not-allowed}@media(max-width:700px){.list article{align-items:flex-start;flex-direction:column}.actions{flex-wrap:wrap}}
</style>
