<script setup>
defineProps({ open: { type: Boolean, default: false }, title: { type: String, default: '' }, inquiry: { type: Object, default: null }, products: { type: Array, default: () => [] }, loading: { type: Boolean, default: false }, error: { type: String, default: '' }, source: { type: String, default: 'inventory' }, method: { type: String, default: 'exact' }, drag: { type: Object, required: true } })
defineEmits(['close', 'start-drag', 'set-source', 'set-method', 'view-chat'])

function waLink(party) {
  const clean = party?.contact_phone?.split('@')[0].replace(/\D/g, '')
  if (!clean) return ''
  const params = new URLSearchParams({ phone: clean })
  if (party.original_text) params.set('text', party.original_text)
  return `whatsapp://send?${params.toString()}`
}

function formatDateTime(value) {
  if (!value) return ''
  try { return new Date(value).toLocaleString() } catch { return '' }
}
</script>

<template><Teleport to="#ui-teleport-host"><div v-if="open" class="backdrop" @click.self="$emit('close')"><section class="dialog" :style="{ transform: `translate(${drag.x}px, ${drag.y}px)` }" role="dialog" aria-modal="true"><header @mousedown="$emit('start-drag', $event)"><div><small>{{ title }}</small><strong>{{ inquiry?.summary || 'Market parties for selected inquiry' }}</strong><span>{{ inquiry?.inquiry_type === 'sell' ? 'Showing parties asking for these products' : 'Showing parties selling these products' }}</span></div><button type="button" @mousedown.stop @click="$emit('close')">×</button></header><div class="body"><nav><button type="button" :class="{ active: source === 'inventory' }" @click="$emit('set-source', 'inventory')">Inventory Matches</button><button type="button" :class="{ active: source === 'non_inventory' }" @click="$emit('set-source', 'non_inventory')">Non-Inventory Tracking</button></nav><nav class="methods"><button v-for="value in ['exact','text','embedding']" :key="value" type="button" :class="{ active: method === value }" @click="$emit('set-method', value)">{{ value[0].toUpperCase() + value.slice(1) }}</button></nav><div v-if="loading" class="state">Loading market offers...</div><div v-else-if="error" class="error">{{ error }}</div><div v-else-if="!products.length" class="state">No product lines available.</div><div v-else class="products"><article v-for="product in products" :key="`${product.index}-${product.product_id || 'unmapped'}`"><div class="product-head"><div><strong>{{ product.product_name || product.canonical_name || `Product line ${product.index + 1}` }}</strong><span>Line {{ product.index + 1 }} · {{ product.action_label === 'selling' ? 'parties selling this item' : 'parties asking for this item' }}</span></div><b>{{ product.parties?.length || 0 }}</b></div><div v-if="product.message" class="state compact">{{ product.message }}</div><div v-else><div v-for="party in product.parties" :key="party.inquiry_product_id" class="party"><div class="party-main"><strong>{{ party.contact_name || 'Unknown contact' }}</strong><div class="meta"><span>{{ party.contact_phone || 'No phone' }}</span><span v-if="party.account_name">· {{ party.account_name }}</span><span v-if="party.source_chat_name">· {{ party.source_chat_name }}</span></div><p>{{ party.original_text || 'No source text' }}</p><div class="facts"><span v-if="party.quantity">Qty {{ party.quantity }}</span><span v-if="party.price">{{ party.currency || '' }} {{ party.price }}</span><span v-if="party.first_seen_at">{{ formatDateTime(party.first_seen_at) }}</span><span v-if="party.distance != null">Distance {{ party.distance }}</span></div></div><div class="party-actions"><button v-if="party.source_chat_id" type="button" @click="$emit('view-chat', party)">Chat →</button><a v-if="waLink(party)" :href="waLink(party)">WA</a></div></div></div></article></div></div></section></div></Teleport></template>

<style scoped>
.backdrop{position:fixed;z-index:1200;inset:0;display:grid;place-items:center;padding:20px;background:var(--ui-overlay)}.dialog{width:min(980px,96vw);max-height:90vh;overflow:auto;border:1px solid var(--ui-border);border-radius:var(--ui-radius-lg);background:var(--ui-surface);box-shadow:var(--ui-shadow-popover)}header{display:flex;align-items:flex-start;justify-content:space-between;padding:16px 18px;border-bottom:1px solid var(--ui-border);cursor:move;user-select:none}header small,header strong,header span{display:block}header small{color:var(--ui-primary);font-weight:800;letter-spacing:.1em;text-transform:uppercase}header strong{margin-top:3px;color:var(--ui-text-strong);font-size:1rem}header span{margin-top:3px;color:var(--ui-text-muted);font-size:.76rem}header button{border:0;background:transparent;color:var(--ui-text-muted);font-size:1.3rem;cursor:pointer}.body{padding:14px 18px 18px}.body nav{display:flex;gap:5px;padding:4px;border-radius:var(--ui-radius-sm);background:var(--ui-surface-muted)}nav.methods{margin-top:7px;background:var(--ui-surface)}nav button{padding:6px 10px;border:0;border-radius:var(--ui-radius-xs);background:transparent;color:var(--ui-text-muted);cursor:pointer}nav button.active{background:var(--ui-primary);color:var(--ui-on-primary)}.state,.error{padding:22px;color:var(--ui-text-muted);text-align:center}.state.compact{padding:10px}.error{color:var(--ui-danger)}.products{display:flex;flex-direction:column;gap:12px;margin-top:12px}.products article{overflow:hidden;border:1px solid var(--ui-border);border-radius:var(--ui-radius-md)}.product-head{display:flex;align-items:center;justify-content:space-between;padding:11px 13px;background:var(--ui-surface-muted)}.product-head strong,.product-head span{display:block}.product-head span{margin-top:2px;color:var(--ui-text-muted);font-size:.73rem}.product-head b{padding:3px 8px;border-radius:var(--ui-radius-pill);background:var(--ui-primary-soft);color:var(--ui-primary)}.party{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:11px 13px;border-top:1px solid var(--ui-border)}.party-main{min-width:0;flex:1}.party-main>strong{color:var(--ui-text-strong)}.meta,.facts{display:flex;flex-wrap:wrap;gap:6px;color:var(--ui-text-muted);font-size:.72rem}.party-main p{margin:5px 0;color:var(--ui-text);font-size:.78rem}.party-actions{display:flex;gap:6px}.party-actions button,.party-actions a{padding:6px 9px;border:1px solid var(--ui-primary);border-radius:var(--ui-radius-xs);background:var(--ui-primary-soft);color:var(--ui-primary);text-decoration:none;cursor:pointer}
</style>
