# Generated by Django 5.2.15 on 2026-10-01 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientpulse', '0001_initial'),
        ('tenancy', '0010_harden_company_contacts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lifecycle_stage', models.CharField(choices=[('lead', 'Lead'), ('prospect', 'Prospect'), ('active_customer', 'Active Customer'), ('dormant', 'Dormant'), ('lost', 'Lost'), ('blocked', 'Blocked')], default='lead', max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('archived', 'Archived')], default='active', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], default='normal', max_length=20)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('whatsapp', 'Whatsapp'), ('google_contacts', 'Google Contacts'), ('import', 'Import'), ('referral', 'Referral'), ('other', 'Other')], default='manual', max_length=30)),
                ('preferred_channel', models.CharField(blank=True, choices=[('whatsapp', 'Whatsapp'), ('email', 'Email'), ('phone', 'Phone'), ('other', 'Other')], max_length=20)),
                ('preferred_language', models.CharField(blank=True, max_length=20)),
                ('timezone', models.CharField(default='Asia/Dubai', max_length=64)),
                ('last_contacted_at', models.DateTimeField(blank=True, null=True)),
                ('last_inbound_at', models.DateTimeField(blank=True, null=True)),
                ('next_follow_up_at', models.DateTimeField(blank=True, null=True)),
                ('do_not_contact', models.BooleanField(default=False)),
                ('do_not_contact_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_profiles', to='tenancy.company')),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to='tenancy.companycontact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_profiles_created', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_client_profiles', to='tenancy.companymembership')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_profiles_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clientpulse_profile',
                'ordering': ['contact__display_name', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_notes', to='tenancy.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_notes_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_notes_updated', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='clientpulse.clientprofile')),
            ],
            options={
                'db_table': 'clientpulse_note',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('inbound_message', 'Inbound Message'), ('outbound_message', 'Outbound Message'), ('note', 'Note'), ('call', 'Call'), ('meeting', 'Meeting'), ('reminder', 'Reminder'), ('status_change', 'Status Change'), ('sequence_event', 'Sequence Event'), ('sync_event', 'Sync Event')], max_length=30)),
                ('occurred_at', models.DateTimeField()),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('channel', models.CharField(blank=True, max_length=30)),
                ('direction', models.CharField(blank=True, max_length=20)),
                ('source_model', models.CharField(blank=True, max_length=100)),
                ('source_id', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_activities', to='tenancy.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_activities_created', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='clientpulse.clientprofile')),
            ],
            options={
                'db_table': 'clientpulse_activity',
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ClientPulseSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('automated_follow_up_enabled', models.BooleanField(default=False)),
                ('consent_mode', models.CharField(choices=[('observational', 'Observational'), ('enforced', 'Enforced')], default='observational', max_length=20)),
                ('reminders_enabled', models.BooleanField(default=True)),
                ('default_timezone', models.CharField(default='Asia/Dubai', max_length=64)),
                ('default_language', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clientpulse_settings', to='tenancy.company')),
            ],
            options={
                'db_table': 'clientpulse_settings',
            },
        ),
        migrations.CreateModel(
            name='ClientTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('normalized_name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#23865b', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_tags', to='tenancy.company')),
            ],
            options={
                'db_table': 'clientpulse_tag',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClientTagAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_tags_assigned', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_tag_assignments', to='tenancy.company')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_assignments', to='clientpulse.clientprofile')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='clientpulse.clienttag')),
            ],
            options={
                'db_table': 'clientpulse_tag_assignment',
            },
        ),
        migrations.CreateModel(
            name='ContactConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=30)),
                ('purpose', models.CharField(choices=[('transactional', 'Transactional'), ('follow_up', 'Follow Up'), ('marketing', 'Marketing')], max_length=30)),
                ('status', models.CharField(choices=[('unknown', 'Unknown'), ('granted', 'Granted'), ('denied', 'Denied'), ('revoked', 'Revoked')], default='unknown', max_length=20)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_consents', to='tenancy.company')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='clientpulse.clientprofile')),
            ],
            options={
                'db_table': 'clientpulse_contact_consent',
                'ordering': ['channel', 'purpose'],
            },
        ),
        migrations.AddIndex(
            model_name='clientprofile',
            index=models.Index(fields=['company', 'lifecycle_stage'], name='cp_profile_stage_idx'),
        ),
        migrations.AddIndex(
            model_name='clientprofile',
            index=models.Index(fields=['company', 'owner'], name='cp_profile_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='clientprofile',
            index=models.Index(fields=['company', 'next_follow_up_at'], name='cp_profile_followup_idx'),
        ),
        migrations.AddIndex(
            model_name='clientprofile',
            index=models.Index(fields=['company', 'last_contacted_at'], name='cp_profile_contacted_idx'),
        ),
        migrations.AddIndex(
            model_name='clientprofile',
            index=models.Index(fields=['company', 'status'], name='cp_profile_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='clientactivity',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('source_model', ''), _negated=True), models.Q(('source_id', ''), _negated=True)), fields=('company', 'profile', 'source_model', 'source_id'), name='unique_client_activity_source'),
        ),
        migrations.AddConstraint(
            model_name='clienttag',
            constraint=models.UniqueConstraint(fields=('company', 'normalized_name'), name='unique_client_tag_name_per_company'),
        ),
        migrations.AddConstraint(
            model_name='clienttagassignment',
            constraint=models.UniqueConstraint(fields=('profile', 'tag'), name='unique_client_profile_tag'),
        ),
        migrations.AddConstraint(
            model_name='contactconsent',
            constraint=models.UniqueConstraint(fields=('company', 'profile', 'channel', 'purpose'), name='unique_client_consent_scope'),
        ),
    ]
