# Generated by Django 5.2.15 on 2026-10-01 18:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientpulse', '0003_seed_clientpulse_settings'),
        ('tenancy', '0010_harden_company_contacts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('due_at', models.DateTimeField()),
                ('timezone', models.CharField(default='Asia/Dubai', max_length=64)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('due', 'Due'), ('completed', 'Completed'), ('snoozed', 'Snoozed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('recurrence_type', models.CharField(choices=[('none', 'None'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom', 'Custom')], default='none', max_length=20)),
                ('recurrence_rule', models.JSONField(blank=True, default=dict)),
                ('snoozed_until', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('next_occurrence_at', models.DateTimeField(blank=True, null=True)),
                ('series_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('occurrence_number', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_client_reminders', to='tenancy.companymembership')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_reminders', to='tenancy.company')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_reminders_completed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_reminders_created', to=settings.AUTH_USER_MODEL)),
                ('previous_occurrence', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_occurrence', to='clientpulse.clientreminder')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='clientpulse.clientprofile')),
            ],
            options={
                'db_table': 'clientpulse_reminder',
                'ordering': ['due_at', '-priority'],
            },
        ),
        migrations.CreateModel(
            name='ClientReminderNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_reminder_notifications', to='tenancy.company')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_reminder_notifications', to='tenancy.companymembership')),
                ('reminder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='clientpulse.clientreminder')),
            ],
            options={
                'db_table': 'clientpulse_reminder_notification',
                'ordering': ['-delivered_at'],
            },
        ),
        migrations.AddIndex(
            model_name='clientreminder',
            index=models.Index(fields=['company', 'status', 'due_at'], name='cp_reminder_due_idx'),
        ),
        migrations.AddIndex(
            model_name='clientreminder',
            index=models.Index(fields=['assigned_to', 'status', 'due_at'], name='cp_reminder_assigned_idx'),
        ),
        migrations.AddIndex(
            model_name='clientreminder',
            index=models.Index(fields=['profile', 'due_at'], name='cp_reminder_profile_idx'),
        ),
        migrations.AddConstraint(
            model_name='clientreminder',
            constraint=models.UniqueConstraint(fields=('series_key', 'occurrence_number'), name='unique_reminder_series_occurrence'),
        ),
    ]
